apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-orchestrator-config
data:
  config.yaml: |
    adapters:
      vnfm: {{ .Values.adapters.vnfManagerEndpoint }}
      sdnc: {{ .Values.adapters.sdncEndpoint }}
      nsmf: {{ .Values.adapters.nsManagerEndpoint }}
    logging:
      level: {{ .Values.env.LOG_LEVEL }}
