apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-orchestrator
  labels:
    app: orchestrator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: "{{ .Values.env.LOG_LEVEL }}"
            - name: CONFIG_FILE
              value: "{{ .Values.env.CONFIG_FILE }}"
          ports:
            - containerPort: {{ .Values.api.restPort }}
            - containerPort: {{ .Values.api.grpcPort }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/orchestrator
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-orchestrator-config
