apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-orchestrator
  labels:
    app: orchestrator
spec:
  selector:
    app: orchestrator
  ports:
    - protocol: TCP
      port: {{ .Values.api.restPort }}
      targetPort: {{ .Values.api.restPort }}
      name: rest
    - protocol: TCP
      port: {{ .Values.api.grpcPort }}
      targetPort: {{ .Values.api.grpcPort }}
      name: grpc
  type: ClusterIP
